name: YouCantHaveThat
version: '1.0.1'
main: me.sintaxlabs.YouCantHaveThat.main
api-version: '1.16'


commands:
  reloadconfig:
    description: Reload the plugin config
    usage: /youcanthavethat <subcommand>
    aliases: [ youcanthavethat, ycht, youcanthave ]
    permission: youcanthavethat.reload

permissions:
  youcanthavethat.bypass:
    description: Allows user to bypass Bad Item Checks.
    default: op
  youcanthavethat.reload:
    description: Allows user to reload YouCantHaveThat.
    default: op